name: build + publish

env:
    CONTEXT_DIR: './'
    IMAGE_NAME: ${{ github.repository }}/c2cpayru
    DOCKERFILE: Dockerfile.staging
    CAPROVER_APP: c2cpayru
    DOCKER_REGISTRY: ghcr.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-caprover:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - run: |
            echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
            export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
            echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GIT_TOKEN }}
  
      - name: Preset Image Name
        run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
  
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_URL }}

      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://c2c-pay.ru
          app: ${{ env.CAPROVER_APP }}
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/captainsvelte/c2cpayru:latest'